	LXI SP, 0000H
	MVI A, 80H	// STOCK VALUE = 128
	CALL WELCOME	// DISPLAY WELCOME MESSAGE
	CALL PRICE	// DISPLAY ENTER THE PRICE

	MVI D,04H
	LXI H,5000H
4INPUTS:CALL READ (CD 75 20) //TAKE 4 DIGIT NUMBER AS INPUT BCD FORM STARTING FROM THE HIGHEST ORDER 
	SUI 30H
	MOV M,A
	INX H
	DCR D
	JNZ 4INPUTS

	LDA 5000H
	MOV L,A
	MVI H,0H	//CONVERT 4TH DIGIT  BY MULTIPLYING IT 3 TIMES WITH A(hex)
	CALL MULT 
	CALL MULT
	CALL MULT
	XCHG   		//MOVE THE CONTENTS IN D AND E REGISTER PAIR
	LDA 5001H	//CONVERT 3TH DIGIT  BY MULTIPLYING IT 2 TIMES WITH AH

	MOV L,A
	MVI H,0H
	CALL MULT 
	CALL MULT 
	DAD D    	//ADD CONTENTS DE AND HL 16 BIT ADDITION 
	XCHG
	LDA 5002H

	MOV L,A
	MVI H,0H
	CALL MULT
	DAD D
	XCHG
	LDA 5003H

	MOV L,A
	MVI H,0H
	DAD D
	SHLD 5050H 	// AMOUNT ENTERED IS STORED IN DE REGISTER PAIR AND THIS ADDRESS
	LXI B, 0000H	//INITIALISE QUOTIENT AS 0000H
 	LHLD 5052H	//LOAD THE DIVISOR IN HL( we have it converted in hex,basically its price of petrol)
		        
LOOP: 	MOV A, E 	//SUBTRACTING UNITS PLACE(1ST BYTE OF DIVIDENED AND DIVISOR)
 	SUB L 	
 	MOV E, A 	
 	MOV A, D 	//SUBTRACTING 2ND BYTE 
	SBB H 	
 	MOV D, A 	
	JC LOOP1 	
 	INX B 	
 	JMP LOOP 	
LOOP1: 	DAD D 	
 	SHLD 5059H 	//storing reaminder IN 5059 
 	MOV L, C 	
 	MOV H, B 	
 	SHLD 5055H 	//storing quotient IN 5055
	CALL CHECK
	LDA 8000H
	CPI 0FFH
	JNZ CONT
	LDA 8500H
	LXI H,5055H
	SUB M
	STA 8500H
	LDA 5055H
	OUT 00H
	LDA 5059H
	OUT 01H
 	RST1
CONT:	CALL ERROR
	RST1

CHECK:  LDA 8500H 
	LXI H,5055H
	SUB M
	JP end	
	MVI A,0F0H
HERE:	STA 8000H 
	RET
end: 	MVI A,0FFH
	JMP HERE

WELCOME(6000H):CALL CRLF(CD 8A 04)    //DISPLAY "WELCOME"
	LXI H, 5700H
	CALL OUTMSG(CD D8 03)
	LXI D FFFFH
	CALL DELAY (CD 15 06)
	RET 

PRICE(6100H): 	CALL CRLF(CD 8A 04)  //DISPLAY "ENTER THE PRICE"
	LXI H, 57A0
	CALL OUTMSG(CD D8 03)
	LXI D FFFFH
	CALL DELAY (CD 15 06)
	RET 

MULT(6200H): 	MVI B,0AH		//SUBROUTINE FOR MULTIPLICATION 
	MVI A,00H
	LOOP2: ADD L
	JNC LOOP
	INR H	
LOOP: 	DCR B
	JNZ LOOP2
	MOV L,A
	RET

ERROR(6300H):	CALL CRLF(CD 8A 04)    //DISPLAY "INSUFFICIENT STOCK"
	LXI H, 57B0H
	CALL OUTMSG(CD D8 03)
	LXI D FFFFH
	CALL DELAY (CD 15 06)
	RET 

